services:
  xray:
    image: teddysun/xray
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - /etc/xray:/etc/xray
    deploy:
      restart_policy:
        condition: always
  nginx:
    image: nginx:alpine
    deploy:
      restart_policy:
        condition: always
